spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://39.104.50.29:7006/spring-cloud-study/remote-config.git
          search-paths: repo
          username: wenhao
          password: wenhao151
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/