spring:
  application:
    name: hello-spring-cloud-eureka
  zipkin:
    base-url: http://localhost:8080
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/